name: File updater for master
on:
  push:
    branches:
      - master

jobs:
  update_commit_id:
    name: Update my file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Display status
        uses: srt32/git-actions@v0.0.3
        args: git status
      - name: Update hello.txt
        run: |
          echo hello > hello.txt
      - name: Add hello.txt
        uses: srt32/git-actions@v0.0.3
        args: git add hello.txt
      - name: Commit hello.txt
        uses: srt32/git-actions@v0.0.3
        args: git commit -m "add hello.txt"
      - name: Push hello.txt
        uses: srt32/git-actions@v0.0.3
        args: git push
