name: GitHub Actions Demo
on:
  push:
    branches:
      - master


jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hello, world!
      run: |
        echo $MY_VAR
